//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOTROMusicManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LOTROMusicManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\adeflang1025\ansi\ansicpg1252\uc1\adeff31507\deff0\stshfdbch31505\stshfloch31506\stshfhich31506\stshfbi31507\deflang1033\deflangfe1033\themelang1033\themelangfe0\themelangcs0{\fonttbl{\f0\fbidi \froman\fcharset0\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f1\fbidi \fswiss\fcharset0\fprq2{\*\panose 020b0604020202020204}Arial;}
        ///{\f2\fbidi \fmodern\fcharset0\fprq1{\*\panose 02070309020205020404}Courier New;}{\f3\fbidi \froman\fcharset2\fprq2{\*\panose 05050102010706020507}Symbol;}{\f23\fbid [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ABCRef {
            get {
                return ResourceManager.GetString("ABCRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A:.
        /// </summary>
        internal static string ABCTagAuthor {
            get {
                return ResourceManager.GetString("ABCTagAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H:.
        /// </summary>
        internal static string ABCTagHistory {
            get {
                return ResourceManager.GetString("ABCTagHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K:.
        /// </summary>
        internal static string ABCTagKey {
            get {
                return ResourceManager.GetString("ABCTagKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W:.
        /// </summary>
        internal static string ABCTagLyrics {
            get {
                return ResourceManager.GetString("ABCTagLyrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M:.
        /// </summary>
        internal static string ABCTagMeter {
            get {
                return ResourceManager.GetString("ABCTagMeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N:.
        /// </summary>
        internal static string ABCTagNote {
            get {
                return ResourceManager.GetString("ABCTagNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O:.
        /// </summary>
        internal static string ABCTagOrigin {
            get {
                return ResourceManager.GetString("ABCTagOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q:.
        /// </summary>
        internal static string ABCTagTempo {
            get {
                return ResourceManager.GetString("ABCTagTempo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T:.
        /// </summary>
        internal static string ABCTagTitle {
            get {
                return ResourceManager.GetString("ABCTagTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z:.
        /// </summary>
        internal static string ABCTagTranscriber {
            get {
                return ResourceManager.GetString("ABCTagTranscriber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L:.
        /// </summary>
        internal static string ABCTagUnit {
            get {
                return ResourceManager.GetString("ABCTagUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOTRO Music Manager.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon LOMM {
            get {
                object obj = ResourceManager.GetObject("LOMM", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \The Lord of the Rings Online\music\.
        /// </summary>
        internal static string MusicSubfolder {
            get {
                return ResourceManager.GetString("MusicSubfolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X:1
        ///T: &lt;your title&gt;
        ///M: 4/4     &lt;Meter&gt;
        ///L: 1/4     &lt;Length of undecorated note&gt;
        ///K: Amin    &lt;Key signature&gt;
        ///Q: 1/4=120 &lt;Tempo&gt;
        ///% Headers below are optional
        ///A: &lt;Author - Carborunda Riverside of the Stoors&gt;
        ///O: &lt;Region of origin - Stock, The Shire, Eriador&gt; 
        ///N: &lt;Any notes you want&gt;
        ///N: &lt;And any more lines of note.&gt;
        ///%
        ///% And now your lovely music...
        ///|ABCD|EFG&gt;^G|[A4a4C4E4]||
        ///.
        /// </summary>
        internal static string NewABC {
            get {
                return ResourceManager.GetString("NewABC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find LOTRO client to send commands.
        /// </summary>
        internal static string NoLOTROFound {
            get {
                return ResourceManager.GetString("NoLOTROFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /play &quot;{0}&quot;.
        /// </summary>
        internal static string PlayFileCommand {
            get {
                return ResourceManager.GetString("PlayFileCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /play &quot;{0}&quot; sync.
        /// </summary>
        internal static string PlaySyncCommand {
            get {
                return ResourceManager.GetString("PlaySyncCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text in the ABC file has changed. Do you want to save the changes?.
        /// </summary>
        internal static string SavePrompt {
            get {
                return ResourceManager.GetString("SavePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /playstart.
        /// </summary>
        internal static string StartSyncCommand {
            get {
                return ResourceManager.GetString("StartSyncCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /music.
        /// </summary>
        internal static string ToggleMusicCommand {
            get {
                return ResourceManager.GetString("ToggleMusicCommand", resourceCulture);
            }
        }
    }
}
